---
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install system packages
  apt:
    name: "{{ system_packages }}"
    state: present
  notify: system updated

- name: Create application directory
  file:
    path: /opt/{{ app_name }}
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"
