---
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install System Packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ system_packages }}"
  notify: system updated

- name: Create application directory
  file:
    path: /app/{{ app_name }}
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"
