all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    webservers:
      hosts:
        server-0-public:
          ansible_host: 13.201.43.72
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/mainkey
        server-1-public:
          ansible_host: 52.66.249.21
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/mainkey
    
    public_servers:
      hosts:
        server-0-public:
          ansible_host: 13.201.43.72
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/mainkey
        server-1-public:
          ansible_host: 52.66.249.21
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/mainkey
    
    private_servers:
      hosts:
        server-0-private:
          ansible_host: 10.123.1.163
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/mainkey
        server-1-private:
          ansible_host: 10.123.2.111
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/mainkey
