all:
  hosts:
    server-0:
      ansible_host: ${server_1}
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/tfkey
    server-1:
      ansible_host: ${server_2}
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/tfkey
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    webservers:
      hosts:
        server-0:
        server-1:
    public_servers:
      hosts:
        server-0:
        server-1:
    private_servers:
      hosts:
        server-0:
          ansible_host: ${pvt_server_1}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/tfkey
        server-1:
          ansible_host: ${pvt_server_2}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/tfkey
