all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    webservers:
      hosts:
        server-0-public:
          ansible_host: ${server_1}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/tfkey
        server-1-public:
          ansible_host: ${server_2}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/tfkey
    public_servers:
      hosts:
        server-0-public:
          ansible_host: ${server_1}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/tfkey
        server-1-public:
          ansible_host: ${server_2}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/tfkey
    private_servers:
      hosts:
        server-0-private:
          ansible_host: ${pvt_server_1}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/tfkey
        server-1-private:
          ansible_host: 10.123.2.59
          ansible_user: ${pvt_server_2}
          ansible_ssh_private_key_file: ~/.ssh/tfkey
