---
- name: Installing packages for python environment
  become: true
  apt:
    name:
      - python3-pip
    update_cache: true

- name: Creates directory
  file:
    path: ./basic-http-server
    state: directory

- name: Install Apache2
  become: true
  apt: name=apache2 state=latest update_cache=true
